name: NuGet Publish

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install SSL dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Build and Pack
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet pack src/OneSignalApi/OneSignalApi.csproj --configuration Release --no-build --output nupkgs
      - name: Publish to NuGet
        run: dotnet nuget push nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
